### ISSUE TITLE
BUG6 - the remote communicated task seems cannot connect to upstream after rescale

### ISSUE THREAD

**Issue by yancanmao** [sane-lab/flink#57]

**Comment by maxCodeVector** [comment]
I find usually it is the case:
| --------------------------------------- |
|                       1/3                    |
| -------------------------------------- |
|                       2/3                    |
| --------------------------------------- |
| `Source`  ---> `3/3`  ---> Sink |
| -----------\--------------------------- |
|                \   `4/4`                    |
| ---------------------------------------|

The bold sub-task could be finished. Only the sub-tasks between arrow have records sent/received.
